image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~muirrum/campmasterconstantine
tasks:
  - setup: |
      rustup toolchain install nightly stable
      cd campmasterconstantine/
      rustup run stable cargo fetch
  - stable: |
      rustup default stable
      cd campmasterconstantine/
      cargo build --verbose
      cargo test --verbose
  - nightly: |
      rustup default nightly
      cd campmasterconstantine/
      cargo build --verbose ||:
      cargo test --verbose  ||: