arch: null
artifacts: []
environment: {}
image: archlinux
packages:
- rustup
repositories: {}
shell: false
sources:
- https://github.com/Discord-Scout-Council/DSC-Bot.git
tasks:
- setup: |
    rustup toolchain install nightly stable
    cd DSC-Bot/
    rustup run stable cargo fetch
- stable: |
    rustup default stable
    cd DSC-Bot/
    cargo build --verbose
    cargo test --verbose
- nightly: |-
    rustup default nightly
    cd DSC-Bot/
    cargo build --verbose ||:
    cargo test --verbose  ||:
triggers: []
